### ISSUE TITLE
Use hex for getters

### ISSUE THREAD

**Issue by tkernell** [tellor-io/layer#646]
Use hex for different getters when they return queryId, queryData, report value, etc

Ex:
```
./layerd query oracle tipped-queries --node=$node2                                      ─╯
queries:
- amount: "59780"
  expiration: "628873"
  has_revealed_reports: true
  id: "313449"
  query_data: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJVFJCQnJpZGdlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABM=
  registry_spec_block_window: "2000"
```

This query_data should be in hex. Check all queries for this behavior.
